version: '3.8'

services:
    nginx:
        image: nginx:1.21.1
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - ./src/public:/var/www/public
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
        - php

    php:
        build: ./docker/php
        volumes:
            - ./src:/var/www/
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=my-rds-instance.ct6iymeq294g.ap-northeast-1.rds.amazonaws.com
            - DB_PORT=3306
            - DB_DATABASE=restaurant_reservation
            - DB_USERNAME=admin
            - DB_PASSWORD=mimika0717

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=my-rds-instance.ct6iymeq294g.ap-northeast-1.rds.amazonaws.com
            - PMA_USER=admin
            - PMA_PASSWORD=mimika0717
        ports:
            - 8080:80
